# Form implementation generated from reading ui file 'addUrl.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 90)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(6, 6, 125, 21))
        self.label.setObjectName("label")
        self.url = QtWidgets.QLineEdit(parent=Form)
        self.url.setGeometry(QtCore.QRect(137, 6, 152, 34))
        self.url.setObjectName("url")
        self.cancelButton = QtWidgets.QPushButton(parent=Form)
        self.cancelButton.setGeometry(QtCore.QRect(6, 46, 84, 38))
        self.cancelButton.setObjectName("cancelButton")
        self.nextButton = QtWidgets.QPushButton(parent=Form)
        self.nextButton.setGeometry(QtCore.QRect(137, 46, 84, 38))
        self.nextButton.setObjectName("nextButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление видео"))
        self.label.setText(_translate("Form", "Введи URL видео"))
        self.cancelButton.setText(_translate("Form", "Отмена"))
        self.nextButton.setText(_translate("Form", "Далее"))
