# Form implementation generated from reading ui file 'completed.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form.resize(370, 120)
        Form.setMinimumSize(QtCore.QSize(370, 120))
        Form.setMaximumSize(QtCore.QSize(370, 120))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dialog-positive.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.complete_pic = QtWidgets.QLabel(parent=Form)
        self.complete_pic.setGeometry(QtCore.QRect(6, 6, 64, 64))
        self.complete_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.complete_pic.setText("")
        self.complete_pic.setPixmap(QtGui.QPixmap("dialog-positive.svg"))
        self.complete_pic.setScaledContents(False)
        self.complete_pic.setObjectName("complete_pic")
        self.mainMenu = QtWidgets.QPushButton(parent=Form)
        self.mainMenu.setGeometry(QtCore.QRect(6, 76, 358, 38))
        self.mainMenu.setMinimumSize(QtCore.QSize(358, 38))
        self.mainMenu.setMaximumSize(QtCore.QSize(358, 38))
        self.mainMenu.setObjectName("mainMenu")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(96, 6, 248, 64))
        self.label.setMinimumSize(QtCore.QSize(248, 64))
        self.label.setMaximumSize(QtCore.QSize(248, 64))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Скачано успешно"))
        self.mainMenu.setText(_translate("Form", "В главное меню"))
        self.label.setText(_translate("Form", "Видео было скачано и сохранено!"))
