# Form implementation generated from reading ui file 'filters.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(802, 106)
        self.minimalLengthSlider = QtWidgets.QSlider(parent=Form)
        self.minimalLengthSlider.setGeometry(QtCore.QRect(187, 7, 84, 20))
        self.minimalLengthSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.minimalLengthSlider.setObjectName("minimalLengthSlider")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(6, 6, 164, 22))
        self.label.setObjectName("label")
        self.setFilter = QtWidgets.QPushButton(parent=Form)
        self.setFilter.setGeometry(QtCore.QRect(6, 62, 164, 38))
        self.setFilter.setObjectName("setFilter")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(6, 34, 169, 22))
        self.label_2.setObjectName("label_2")
        self.maximalLengthSlider = QtWidgets.QSlider(parent=Form)
        self.maximalLengthSlider.setGeometry(QtCore.QRect(187, 35, 84, 20))
        self.maximalLengthSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.maximalLengthSlider.setObjectName("maximalLengthSlider")
        self.minimalLengthLabel = QtWidgets.QLabel(parent=Form)
        self.minimalLengthLabel.setGeometry(QtCore.QRect(410, 10, 391, 22))
        self.minimalLengthLabel.setObjectName("minimalLengthLabel")
        self.maximalLengthLabel = QtWidgets.QLabel(parent=Form)
        self.maximalLengthLabel.setGeometry(QtCore.QRect(415, 34, 381, 22))
        self.maximalLengthLabel.setObjectName("maximalLengthLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Минимальная длина"))
        self.setFilter.setText(_translate("Form", "Установить фильтр"))
        self.label_2.setText(_translate("Form", "Максимальная длина"))
        self.minimalLengthLabel.setText(_translate("Form", "TextLabel"))
        self.maximalLengthLabel.setText(_translate("Form", "TextLabel"))
