# Form implementation generated from reading ui file 'formats.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 350)
        self.audioRadioButton = QtWidgets.QRadioButton(parent=Form)
        self.audioRadioButton.setEnabled(True)
        self.audioRadioButton.setGeometry(QtCore.QRect(320, 60, 113, 25))
        self.audioRadioButton.setMouseTracking(False)
        self.audioRadioButton.setTabletTracking(False)
        self.audioRadioButton.setCheckable(True)
        self.audioRadioButton.setChecked(False)
        self.audioRadioButton.setAutoExclusive(True)
        self.audioRadioButton.setObjectName("audioRadioButton")
        self.videoFrame = QtWidgets.QFrame(parent=Form)
        self.videoFrame.setGeometry(QtCore.QRect(40, 90, 151, 181))
        self.videoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.videoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.videoFrame.setObjectName("videoFrame")
        self.radio720 = QtWidgets.QRadioButton(parent=self.videoFrame)
        self.radio720.setGeometry(QtCore.QRect(10, 40, 113, 25))
        self.radio720.setObjectName("radio720")
        self.radio1080 = QtWidgets.QRadioButton(parent=self.videoFrame)
        self.radio1080.setGeometry(QtCore.QRect(0, 80, 113, 25))
        self.radio1080.setObjectName("radio1080")
        self.videoFormatsFrame = QtWidgets.QFrame(parent=self.videoFrame)
        self.videoFormatsFrame.setGeometry(QtCore.QRect(20, 120, 120, 80))
        self.videoFormatsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.videoFormatsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.videoFormatsFrame.setObjectName("videoFormatsFrame")
        self.radioMOV = QtWidgets.QRadioButton(parent=self.videoFormatsFrame)
        self.radioMOV.setGeometry(QtCore.QRect(10, 20, 113, 25))
        self.radioMOV.setObjectName("radioMOV")
        self.radioMP4 = QtWidgets.QRadioButton(parent=self.videoFormatsFrame)
        self.radioMP4.setGeometry(QtCore.QRect(40, 40, 113, 25))
        self.radioMP4.setObjectName("radioMP4")
        self.videoRadioButton = QtWidgets.QRadioButton(parent=Form)
        self.videoRadioButton.setGeometry(QtCore.QRect(70, 50, 113, 25))
        self.videoRadioButton.setObjectName("videoRadioButton")
        self.audioFrame = QtWidgets.QFrame(parent=Form)
        self.audioFrame.setEnabled(True)
        self.audioFrame.setGeometry(QtCore.QRect(290, 170, 120, 80))
        self.audioFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.audioFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.audioFrame.setObjectName("audioFrame")
        self.radio192 = QtWidgets.QRadioButton(parent=self.audioFrame)
        self.radio192.setGeometry(QtCore.QRect(10, 0, 113, 25))
        self.radio192.setObjectName("radio192")
        self.frame = QtWidgets.QFrame(parent=self.audioFrame)
        self.frame.setGeometry(QtCore.QRect(30, 20, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.radioMP3 = QtWidgets.QRadioButton(parent=self.frame)
        self.radioMP3.setGeometry(QtCore.QRect(10, 10, 113, 25))
        self.radioMP3.setObjectName("radioMP3")
        self.radioWAV = QtWidgets.QRadioButton(parent=self.frame)
        self.radioWAV.setGeometry(QtCore.QRect(10, 40, 113, 25))
        self.radioWAV.setObjectName("radioWAV")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 300, 100, 38))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.audioRadioButton.setText(_translate("Form", "Аудио"))
        self.radio720.setText(_translate("Form", "720p"))
        self.radio1080.setText(_translate("Form", "1080p"))
        self.radioMOV.setText(_translate("Form", "mov"))
        self.radioMP4.setText(_translate("Form", "mp4"))
        self.videoRadioButton.setText(_translate("Form", "Видео"))
        self.radio192.setText(_translate("Form", "192 kbps"))
        self.radioMP3.setText(_translate("Form", "mp3"))
        self.radioWAV.setText(_translate("Form", "wav"))
        self.pushButton.setText(_translate("Form", "Скачать"))
