# Form implementation generated from reading ui file 'formats.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 350)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 300, 100, 38))
        self.pushButton.setObjectName("pushButton")
        self.typeFrame = QtWidgets.QFrame(parent=Form)
        self.typeFrame.setGeometry(QtCore.QRect(50, 20, 120, 80))
        self.typeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.typeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.typeFrame.setObjectName("typeFrame")
        self.videoRadioButton = QtWidgets.QRadioButton(parent=self.typeFrame)
        self.videoRadioButton.setGeometry(QtCore.QRect(10, 10, 113, 25))
        self.videoRadioButton.setObjectName("videoRadioButton")
        self.qualityFrame = QtWidgets.QFrame(parent=Form)
        self.qualityFrame.setGeometry(QtCore.QRect(40, 110, 351, 80))
        self.qualityFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.qualityFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.qualityFrame.setObjectName("qualityFrame")
        self.radio720 = QtWidgets.QRadioButton(parent=self.qualityFrame)
        self.radio720.setGeometry(QtCore.QRect(10, 10, 113, 25))
        self.radio720.setObjectName("radio720")
        self.radio192 = QtWidgets.QRadioButton(parent=self.qualityFrame)
        self.radio192.setGeometry(QtCore.QRect(190, 10, 113, 25))
        self.radio192.setObjectName("radio192")
        self.radio1080 = QtWidgets.QRadioButton(parent=self.qualityFrame)
        self.radio1080.setGeometry(QtCore.QRect(10, 40, 113, 25))
        self.radio1080.setObjectName("radio1080")
        self.formatFrame = QtWidgets.QFrame(parent=Form)
        self.formatFrame.setGeometry(QtCore.QRect(40, 180, 351, 101))
        self.formatFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.formatFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.formatFrame.setObjectName("formatFrame")
        self.radioMP3 = QtWidgets.QRadioButton(parent=self.formatFrame)
        self.radioMP3.setGeometry(QtCore.QRect(200, 20, 113, 25))
        self.radioMP3.setObjectName("radioMP3")
        self.radioMP4 = QtWidgets.QRadioButton(parent=self.formatFrame)
        self.radioMP4.setGeometry(QtCore.QRect(0, 20, 113, 25))
        self.radioMP4.setObjectName("radioMP4")
        self.radioMOV = QtWidgets.QRadioButton(parent=self.formatFrame)
        self.radioMOV.setGeometry(QtCore.QRect(0, 50, 113, 25))
        self.radioMOV.setObjectName("radioMOV")
        self.radioWAV = QtWidgets.QRadioButton(parent=self.formatFrame)
        self.radioWAV.setGeometry(QtCore.QRect(210, 50, 113, 25))
        self.radioWAV.setObjectName("radioWAV")
        self.audioRadioButton = QtWidgets.QRadioButton(parent=Form)
        self.audioRadioButton.setEnabled(True)
        self.audioRadioButton.setGeometry(QtCore.QRect(230, 40, 113, 25))
        self.audioRadioButton.setMouseTracking(False)
        self.audioRadioButton.setTabletTracking(False)
        self.audioRadioButton.setCheckable(True)
        self.audioRadioButton.setChecked(False)
        self.audioRadioButton.setAutoExclusive(True)
        self.audioRadioButton.setObjectName("audioRadioButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Скачать"))
        self.videoRadioButton.setText(_translate("Form", "Видео"))
        self.radio720.setText(_translate("Form", "720p"))
        self.radio192.setText(_translate("Form", "192 kbps"))
        self.radio1080.setText(_translate("Form", "1080p"))
        self.radioMP3.setText(_translate("Form", "mp3"))
        self.radioMP4.setText(_translate("Form", "mp4"))
        self.radioMOV.setText(_translate("Form", "mov"))
        self.radioWAV.setText(_translate("Form", "wav"))
        self.audioRadioButton.setText(_translate("Form", "Аудио"))
