# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_YoutubeDownloader(object):
    def setupUi(self, YoutubeDownloader):
        YoutubeDownloader.setObjectName("YoutubeDownloader")
        YoutubeDownloader.resize(305, 120)
        YoutubeDownloader.setMinimumSize(QtCore.QSize(305, 120))
        YoutubeDownloader.setMaximumSize(QtCore.QSize(16777215, 120))
        self.menuBar = QtWidgets.QMenuBar(parent=YoutubeDownloader)
        self.menuBar.setGeometry(QtCore.QRect(6, 6, 214, 30))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(parent=self.menuBar)
        self.menu.setObjectName("menu")
        self.downloadButton = QtWidgets.QPushButton(parent=YoutubeDownloader)
        self.downloadButton.setGeometry(QtCore.QRect(6, 81, 293, 33))
        self.downloadButton.setObjectName("downloadButton")
        self.address = QtWidgets.QLineEdit(parent=YoutubeDownloader)
        self.address.setGeometry(QtCore.QRect(6, 42, 293, 33))
        self.address.setObjectName("address")
        self.author = QtGui.QAction(parent=YoutubeDownloader)
        self.author.setObjectName("author")
        self.program = QtGui.QAction(parent=YoutubeDownloader)
        self.program.setObjectName("program")
        self.menu.addAction(self.program)
        self.menu.addAction(self.author)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(YoutubeDownloader)
        QtCore.QMetaObject.connectSlotsByName(YoutubeDownloader)

    def retranslateUi(self, YoutubeDownloader):
        _translate = QtCore.QCoreApplication.translate
        YoutubeDownloader.setWindowTitle(_translate("YoutubeDownloader", "Youtube Downloader"))
        self.menu.setTitle(_translate("YoutubeDownloader", "О программе"))
        self.downloadButton.setText(_translate("YoutubeDownloader", "Скачать"))
        self.address.setPlaceholderText(_translate("YoutubeDownloader", "Введи ссылку на видео/плейлист..."))
        self.author.setText(_translate("YoutubeDownloader", "О авторе"))
        self.program.setText(_translate("YoutubeDownloader", "О программе"))
