# Form implementation generated from reading ui file 'video-or-shorts.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 198)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.downloadShorts = QtWidgets.QPushButton(parent=Dialog)
        self.downloadShorts.setObjectName("downloadShorts")
        self.gridLayout.addWidget(self.downloadShorts, 1, 1, 1, 1)
        self.downloadVideo = QtWidgets.QPushButton(parent=Dialog)
        self.downloadVideo.setObjectName("downloadVideo")
        self.gridLayout.addWidget(self.downloadVideo, 1, 0, 1, 1)
        self.downloadAll = QtWidgets.QPushButton(parent=Dialog)
        self.downloadAll.setObjectName("downloadAll")
        self.gridLayout.addWidget(self.downloadAll, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.downloadShorts.setText(_translate("Dialog", "Скачать только Shorts"))
        self.downloadVideo.setText(_translate("Dialog", "Скачать только видео"))
        self.downloadAll.setText(_translate("Dialog", "Скачать всё"))
        self.label.setText(_translate("Dialog", "На канале есть обычные видео и Shorts."))
